import { afterEach, expect, it } from 'vitest';
import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import migration from './356-zen-comparison-coverage.js';

let rootDir;
afterEach(async () => { if (rootDir) await rm(rootDir, { recursive: true, force: true }); });
it('upgrades an existing catalog without losing researched evidence and fails closed on future versions', async () => {
  rootDir = await mkdtemp(join(tmpdir(), 'portos-zen-seed-'));
  await mkdir(join(rootDir, 'data'));
  await mkdir(join(rootDir, 'data.reference'));
  const seed = JSON.parse(await readFile(new URL('../../data.reference/model-comparison.json', import.meta.url), 'utf8'));
  await writeFile(join(rootDir, 'data.reference/model-comparison.json'), JSON.stringify(seed));
  expect(await migration.up({ rootDir })).toEqual({ added: 0 });
  const zen = seed.observations.filter(row => row.provider === 'OpenCode Zen');
  expect(zen).toHaveLength(8);
  expect(zen.every(row => row.quality === null && row.tokensPerSecond === null && row.inputPerMillion.value === 0)).toBe(true);
  const researched = { ...zen[0], notes: 'Example locally researched evidence' };
  const prior = { schemaVersion: 1, observations: [seed.observations[0], researched] };
  const path = join(rootDir, 'data/model-comparison.json');
  await writeFile(path, JSON.stringify(prior));
  expect(await migration.up({ rootDir })).toEqual({ added: 7 });
  const result = JSON.parse(await readFile(path, 'utf8'));
  expect(result.observations.slice(0, 2)).toEqual(prior.observations);
  expect(await migration.up({ rootDir })).toEqual({ added: 0 });
  const future = JSON.stringify({ ...prior, schemaVersion: 99 });
  await writeFile(path, future);
  await expect(migration.up({ rootDir })).rejects.toThrow();
  expect(await readFile(path, 'utf8')).toBe(future);
});
